### ISSUE TITLE
Textures not working in OpenGL 1.1

### ISSUE THREAD

**Issue by ghost** [Sleaker/Cubed#4]
https://github.com/Sleaker/Cubed/issues/3

Excuse me by explain wrong in this topic, my PC has video card onboard and uses Intel G31/G33 Express Chipset Family, so this is OpenGL 1 and consequent does not support shadows, filters, etc... I run your code but as you can see in the images topic, it was all White, I think is there with TextureArray, your custom material or something.

Note: Cubes framework runs fine

**Comment by Sleaker** [comment]
As is noted in my sourcecode, you need a GPU capable of handling 2d texture arrays, which means opengl 3.x+.  My examples are not compatible with very old cards that do not support modern GPU commands. Any GPU that has been manufactured within the last decade should be able to run my example. This means a GeForce 8x00 series card from 2006 and above would work, or Radeon HD2000 series card.  An intel G31 most definitely will not work.
